apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-vsvc
spec:
  gateways:
  - rollouts-demo-gateway
  hosts:
  - "*"
  http:
  - name: primary
    route:
    - destination:
        host: rollouts-demo-stable
      weight: 100                 # Argo Rollouts modifies this
    - destination:
        host: rollouts-demo-canary
      weight: 0                   # Argo Rollouts modifies this