apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-canary
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
  # This selector will be updated with the pod-template-hash of the canary ReplicaSet. e.g.:
  # rollouts-pod-template-hash: 7bf84f9696

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-stable
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
  # This selector will be updated with the pod-template-hash of the canary ReplicaSet. e.g.:
  # rollouts-pod-template-hash: 7bf84f9696